### ISSUE TITLE
Luxmark 3.1x cmd line doesn't print any logs on Windows

### ISSUE THREAD

**Issue by albintho** [LuxCoreRender/LuxMark#13]
As per documentation, Luxmark app should print stdout and stderr to console and exit. Currently, its not printing anything to the console.

--single-run (run the benchmark, print the result to the stdout and exit)

cmd used: start /WAIT /max luxmark.exe --scene="LUXBALL_HDR" --mode="BENCHMARK_OCL_CPUGPU" --single-run --ext-info

**Comment by albintho** [comment]
Even luxmark v4.x also behaves the same way, the score popup appears for a fraction of a second and the benchmark exists rather than printing the scores to the console.

**Comment by Dade916** [comment]
Redirect the out to a file with something like  ">result.txt" and it will work: it is a Windows problem, it doesn't happen on Linux or MacOS.

**Comment by albintho** [comment]
Thanks redirecting the out to a file worked.
