### ISSUE TITLE
LuxMark 3.1 not print result to stdout with --single-run option

### ISSUE THREAD

**Issue by lzp729** [LuxCoreRender/LuxMark#3]
windows 10 x64 OS, LuxMark release v3.1
open cmd windows, run command line:
> luxmark.exe --scene=LUXBALL_HDR --mode=BENCHMARK_OCL_GPU --single-run --ext-info
I found no score result is printed after benchmark finish and luxmark window closed.

**Comment by Dade916** [comment]
It is a Windows culprit, just redirect the output to a file and it will work. Something like:

`luxmark.exe --scene=LUXBALL_HDR --mode=BENCHMARK_OCL_GPU --single-run --ext-info > result.txt
`

**Comment by lzp729** [comment]
thanks @Dade916 , it works!
